; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32dev
framework = arduino
lib_ldf_mode = deep
lib_deps = 
	EEPROM
	Map
	Stack
	Wire
	SPI
	LittleFS
	mikalhart/TinyGPSPlus@^1.0.3
	fastled/FastLED@^3.6.0
	bblanchon/StreamUtils@^1.7.3
	madhephaestus/ESP32Encoder@^0.10.1
	bblanchon/ArduinoJson@^7.0.0
	adafruit/Adafruit HMC5883 Unified@^1.2.1
	adafruit/Adafruit BusIO@^1.14.1
	adafruit/Adafruit Unified Sensor@^1.1.9
	adafruit/Adafruit GFX Library@^1.11.5
	adafruit/Adafruit SSD1306@^2.5.7
	https://github.com/digint/tinyfsm.git
	mathieucarbou/ESPAsyncWebServer@^3.6.0
	ropg/ezTime@0.8.3
build_flags = 
	"-Iinclude/*",
	"-Iinclude/HelperClasses/*",
	"-Iinclude/HelperClasses/LED_Patterns/*",
	"-Iinclude/HelperClasses/OLED_Content/*",
	"-Iinclude/HelperClasses/OLED_Window/*",
	"-Iinclude/HelperClasses/Window_States/*",
	"-Iinclude/HelperClasses/Message_Types/*",
	"-Iinclude/ModuleManagers/*",
	"-Iinclude/Utilities/*",
	"-Isrc/*",
	"-Isrc/HelperClasses/*",
	"-Isrc/HelperClasses/LED_Patterns/*",
	"-Isrc/HelperClasses/OLED_Content/*",
	"-Isrc/HelperClasses/OLED_Window/*",
	"-Isrc/HelperClasses/Window_States/*",
	"-Isrc/ModuleManagers/*",
	"-Isrc/Utilities/*",
